"""
inspect_paper_data.py — print schema of downloaded paper test data.

Reads the 3 files from `FedE/paper_test_data/` and prints:
  * top-level type (list vs dict)
  * length / count of records
  * first record keys + sample (truncated)
  * inferred schema annotations

Writes a Markdown summary to `FedE/paper_test_data/SCHEMA.md` for future
reference (so the eval script doesn't have to re-inspect).

Run from repo root: python FedE/scripts/inspect_paper_data.py
"""
import json
import os
from io import StringIO

DATA_DIR = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "paper_test_data")
)

FILES = [
    ("val_qa_data_50.json", "Validation queries (50 — paper Table III)"),
    ("test_qa_data_100.json", "Test queries (100 — paper Table II)"),
    ("test_corpus.json", "Retrieval corpus (~6,656 pages)"),
]


def _truncate(s: str, n: int = 200) -> str:
    s = str(s)
    return s if len(s) <= n else s[:n] + "..."


def _summarize(data, name: str, out: StringIO):
    """Append schema summary for one file to `out`."""
    out.write(f"\n## {name}\n\n")
    out.write(f"- top-level type: `{type(data).__name__}`\n")

    if isinstance(data, list):
        out.write(f"- length: **{len(data):,}** records\n")
        if len(data) == 0:
            out.write("- EMPTY LIST — investigate.\n")
            return
        first = data[0]
        out.write(f"- first record type: `{type(first).__name__}`\n")
        if isinstance(first, dict):
            out.write(f"- first record keys: {sorted(first.keys())}\n\n")
            out.write("**Sample first record:**\n```json\n")
            out.write(json.dumps(first, indent=2, ensure_ascii=False)[:2000])
            out.write("\n```\n")

            # Detect nested keys 1-2 levels deep
            for key, val in first.items():
                if isinstance(val, dict):
                    out.write(f"\n- `{key}` is a dict with keys: {sorted(val.keys())}\n")
                    for k2, v2 in val.items():
                        if isinstance(v2, list) and v2 and isinstance(v2[0], dict):
                            out.write(
                                f"  - `{key}.{k2}` is a list of dicts; "
                                f"item keys: {sorted(v2[0].keys())}\n"
                            )

    elif isinstance(data, dict):
        keys = list(data.keys())
        out.write(f"- top-level keys: **{len(keys):,}** total\n")
        out.write(f"- first 5 keys: {keys[:5]}\n")
        if keys:
            first_v = data[keys[0]]
            out.write(f"- first value type: `{type(first_v).__name__}`\n")
            if isinstance(first_v, list):
                out.write(f"- first value list length: {len(first_v)}\n")
                if first_v and isinstance(first_v[0], dict):
                    out.write(
                        f"- first value list[0] keys: {sorted(first_v[0].keys())}\n\n"
                    )
                    out.write("**Sample first value list[0]:**\n```json\n")
                    out.write(json.dumps(first_v[0], indent=2, ensure_ascii=False)[:1500])
                    out.write("\n```\n")
                elif first_v and isinstance(first_v[0], str):
                    out.write(
                        f"- first value list[0] (str, truncated): "
                        f"`{_truncate(first_v[0], 200)}`\n"
                    )
            elif isinstance(first_v, dict):
                out.write(f"- first value (dict) keys: {sorted(first_v.keys())}\n\n")
                out.write("**Sample first value:**\n```json\n")
                out.write(json.dumps(first_v, indent=2, ensure_ascii=False)[:1500])
                out.write("\n```\n")
            elif isinstance(first_v, str):
                out.write(f"- first value (str, truncated): `{_truncate(first_v, 200)}`\n")
    else:
        out.write(f"- unsupported top-level type: {type(data).__name__}\n")


def main():
    out = StringIO()
    out.write("# FedE4RAG Paper Test Data — Schema Inspection\n\n")
    out.write(
        "Auto-generated by `FedE/scripts/inspect_paper_data.py`. "
        "Do not edit by hand — re-run script after re-downloading data.\n"
    )

    for filename, description in FILES:
        path = os.path.join(DATA_DIR, filename)
        if not os.path.exists(path):
            out.write(f"\n## {filename} — MISSING (run download_paper_data.py first)\n")
            print(f"  MISSING: {path}")
            continue

        size_mb = os.path.getsize(path) / (1024 * 1024)
        print(f"\n========= {filename} =========")
        print(f"  Description: {description}")
        print(f"  Size: {size_mb:.2f} MB")

        with open(path, encoding="utf-8") as f:
            data = json.load(f)

        # Print to stdout
        print(f"  Top-level type: {type(data).__name__}")
        if isinstance(data, list):
            print(f"  Length: {len(data):,}")
            if data and isinstance(data[0], dict):
                print(f"  First record keys: {sorted(data[0].keys())}")
                for k, v in data[0].items():
                    print(f"    {k}: {_truncate(v, 100)}")
        elif isinstance(data, dict):
            print(f"  Top-level keys count: {len(data)}")
            keys = list(data.keys())[:5]
            print(f"  First 5 keys: {keys}")
            if keys:
                first_v = data[keys[0]]
                print(f"  First value type: {type(first_v).__name__}")
                if isinstance(first_v, list):
                    print(f"  First value list length: {len(first_v)}")

        # Write structured summary to SCHEMA.md
        full_desc = f"{filename} — {description}"
        _summarize(data, full_desc, out)

    schema_path = os.path.join(DATA_DIR, "SCHEMA.md")
    with open(schema_path, "w", encoding="utf-8") as f:
        f.write(out.getvalue())

    print()
    print(f"Schema summary written to: {schema_path}")


if __name__ == "__main__":
    main()
