[program:sda_job]
command=/opt/supervisor-scripts/sda-job.sh
autostart=false
autorestart=false
startsecs=0
stopasgroup=true
killasgroup=true
stdout_logfile=/workspace/sda-job-supervisor.log
redirect_stderr=true
stdout_logfile_maxbytes=0
